Applications/MPExtended.Applications.WebMediaPortal/Models/StatusViewModels.cs
#region Copyright (C) 2012-2013 MPExtended
// Copyright (C) 2012-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MoreLinq;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Strings;
using MPExtended.Services.Common.Interfaces;
using MPExtended.Services.StreamingService.Interfaces;
using MPExtended.Services.TVAccessService.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Models
{
    public class StatusViewModel
    {
        public bool HasMAS { get { return Connections.Current.HasMASConnection; } }
        public bool HasTAS { get { return Connections.Current.HasTASConnection; } }

        public IEnumerable<TVCardViewModel> Cards { get; private set; }
        public IEnumerable<WebDiskSpaceInformation> DiskInformation { get; private set; }

        public bool HasSystemInformation { get; set; }
        public long TotalMemoryMegaBytes { get; set; }
        public long UsedMemoryMegaBytes { get; set; }
        public int CpuUsage { get; set; }

        public StatusViewModel()
        {
            DiskInformation = new List<WebDiskSpaceInformation>();
        }

        public void SetCardList(IEnumerable<WebCard> cards, IEnumerable<WebVirtualCard> activeCards)
        {
            Cards = new List<TVCardViewModel>();

            foreach (var card in cards.OrderBy(c => c.Id))
            {
                var match = activeCards.Where(vc => vc.Id == card.Id);
                if (match.Any())
                {
                    ((List<TVCardViewModel>)Cards).AddRange(match.Select(vc => new TVCardViewModel(card, vc)));
                }
                else
                {
                    ((List<TVCardViewModel>)Cards).Add(new TVCardViewModel(card));
                }
            }
        }

        public void SetDiskInfo(IEnumerable<WebDiskSpaceInformation> diskInfo)
        {
            DiskInformation = diskInfo;
        }

        public void AddDiskInfo(IEnumerable<WebDiskSpaceInformation> diskInfo)
        {
            DiskInformation = DiskInformation.Concat(diskInfo).DistinctBy(x => x.Disk);
        }
    }

    public class TVCardViewModel
    {
        public int CardId { get; private set; }
        public string Name { get; private set; }
        public string State { get; private set; }

        public bool IsActive { get; private set; }
        public WebVirtualCard VirtualCard { get; private set; }

        public bool GrabbingEPG { get; private set; }
        public bool Scrambled { get; private set; }
        public string Username { get; private set; }
        public int ChannelId { get; private set; }

        public string ChannelName
        {
            get
            {
                return ChannelId > 0 ? Connections.Current.TAS.GetChannelDetailedById(ChannelId).Title : String.Empty;
            }
        }

        public TVCardViewModel(WebCard card)
        {
            CardId = card.Id;
            Name = card.Name;

            IsActive = false;
            State = FormStrings.StateIdle;
            GrabbingEPG = false;
            Scrambled = false;
            ChannelId = 0;
        }

        public TVCardViewModel(WebCard card, WebVirtualCard activeCard)
            : this(card)
        {
            IsActive = true;
            VirtualCard = activeCard;

            GrabbingEPG = activeCard.IsGrabbingEpg;
            Scrambled = activeCard.IsScrambled;
            Username = activeCard.User.Name;
            ChannelId = activeCard.ChannelId;

            if (activeCard.IsTimeShifting) State = FormStrings.StateTimeshifting;
            if (activeCard.IsRecording) State = FormStrings.StateRecording;
            if (activeCard.IsScanning) State = FormStrings.StateScanning;
        }

        public IEnumerable<string> GetRTSPClients()
        {
            if (!IsActive)
                return new List<string>();

            Uri uri = new Uri(VirtualCard.RTSPUrl);
            return Connections.Current.TAS.GetStreamingClients()
                .Where(client => client.StreamName == uri.LocalPath.Substring(1))
                .Select(client => client.IpAdress);
        }

        public IEnumerable<string> GetMPExtendedClients()
        {
            return Connections.Current.TASStreamControl.GetStreamingSessions()
                .Where(x => x.SourceType == WebMediaType.TV && VirtualCard.User.Name == "mpextended-" + x.Identifier)
                .Select(x => x.ClientIPAddress);
        }

        public IEnumerable<string> GetAllClients()
        {
            return GetRTSPClients().Concat(GetMPExtendedClients());
        }
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Controllers/StatusController.cs
#region Copyright (C) 2012-2013 MPExtended
// Copyright (C) 2012-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Management;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Libraries.Service;
using MPExtended.Services.Common.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    [ServiceAuthorize]
    public class StatusController : BaseController
    {
        private static PerformanceCounter cpuCounter = new PerformanceCounter();
        private static PerformanceCounter memoryCounter = new PerformanceCounter();
        private static int totalMemory;

        static StatusController()
        {
            totalMemory = (int)(GetTotalMemoryBytes() / 1024 / 1024);
            cpuCounter.CategoryName = "Processor";
            cpuCounter.CounterName = "% Processor Time";
            cpuCounter.InstanceName = "_Total";
            memoryCounter.CategoryName = "Memory";
            memoryCounter.CounterName = "Available MBytes";
        }

        private static long GetTotalMemoryBytes()
        {
            ObjectQuery objectQuery = new ObjectQuery("SELECT TotalPhysicalMemory from Win32_ComputerSystem");
            ManagementObjectSearcher searcher = new ManagementObjectSearcher(objectQuery);
            var enumerator = searcher.Get().GetEnumerator();
            if (!enumerator.MoveNext()) return 0;
            return Convert.ToInt64(enumerator.Current["TotalPhysicalMemory"]);
        }

        //
        // GET: /Status/
        public ActionResult Index()
        {
            var model = new StatusViewModel();

            if (Connections.Current.HasTASConnection)
            {
                model.AddDiskInfo(Connections.Current.TAS.GetAllRecordingDiskInformation());
                model.AddDiskInfo(Connections.Current.TAS.GetLocalDiskInformation());
                model.SetCardList(Connections.Current.TAS.GetCards(), Connections.Current.TAS.GetActiveCards());
            }

            if (Connections.Current.HasMASConnection)
            {
                model.AddDiskInfo(Connections.Current.MAS.GetLocalDiskInformation());
            }

            try
            {
                model.CpuUsage = (int)Math.Round(cpuCounter.NextValue());
                model.TotalMemoryMegaBytes = totalMemory;
                model.UsedMemoryMegaBytes = (int)Math.Round(totalMemory - memoryCounter.NextValue());
                model.HasSystemInformation = true;
            }
            catch (UnauthorizedAccessException)
            {
                Log.Info("Failed to read performance counters, got UnauthorizedAccessException");
                model.HasSystemInformation = false;
            }
            catch (Exception ex)
            {
                Log.Info("Failed to read performance counters", ex);
                model.HasSystemInformation = false;
            }

            return View(model);
        }

        public ActionResult Stop(string user)
        {
            Connections.Current.TAS.CancelCurrentTimeShifting(user);
            return RedirectToAction("Index");
        }

        public ActionResult Details(string user)
        {
            var vcard = Connections.Current.TAS.GetActiveCards().Where(vc => vc.User.Name == user).FirstOrDefault();
            if (vcard == null)
                return HttpNotFound();

            var card = Connections.Current.TAS.GetCards().Where(c => c.Id == vcard.Id).FirstOrDefault();
            if (card == null)
                return HttpNotFound();

            return View(new TVCardViewModel(card, vcard));
        }

        public JsonResult GetPerformanceCounters()
        {
            // No exception handling needed anymore, because we already check whether performance counters work in Index()
            var returnObject = new
            {
                CPU = (int)Math.Round(cpuCounter.NextValue()),
                Memory = (int)Math.Round(totalMemory - memoryCounter.NextValue())
            };
            return Json(returnObject, JsonRequestBehavior.AllowGet);
        } 
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/Status/Details.cshtml
@model TVCardViewModel
@{
    ViewBag.Title = UIStrings.CardDetails;
}

<h2>@UIStrings.CardDetails</h2>

<table class="webmp">
    <tr><th colspan="2">@UIStrings.CardDetails</th></tr>
    <tr><td>@UIStrings.Card</td><td>@Model.CardId</td></tr>
    <tr><td>@UIStrings.CardName</td><td>@Model.Name</td></tr>
    <tr><td>@UIStrings.CardState</td><td>@Model.State</td></tr>
    <tr><td>@UIStrings.Channel</td><td>@Model.ChannelName</td></tr>
    <tr><td>@UIStrings.CardGrabbingEPG</td><td>@(Model.GrabbingEPG ? UIStrings.Yes : UIStrings.No)</td></tr>
    <tr><td>@UIStrings.CardScrambled</td><td>@(Model.Scrambled ? UIStrings.Yes : UIStrings.No)</td></tr>
    @if (Model.VirtualCard.IsTimeShifting)
    {
        <tr><td>@UIStrings.CardTimeshiftingFile</td><td>@Model.VirtualCard.TimeShiftFileName</td></tr>
    }
    @if (Model.VirtualCard.IsRecording)
    {
        <tr><td>@UIStrings.CardRecordingFile</td><td>@Model.VirtualCard.RecordingFileName</td></tr>
    }
    <tr><td>@UIStrings.CardRTSPStream</td><td>@Model.VirtualCard.RTSPUrl</td></tr>
    <tr><td>@UIStrings.Username</td><td>@Model.Username</td></tr>
    @if (!Model.VirtualCard.IsRecording) {
        <tr><td colspan="2">@Html.ActionLink(UIStrings.Stop, "Stop", new { user = Model.Username })</td></tr>
    }
</table>
<br />

@{
    var clients = Model.GetAllClients();
    if(clients.Any())
    {
        <h2>@UIStrings.StreamingClients</h2>
        <ul>
            @foreach (var ipAddress in clients)
            {
                <li>@ipAddress</li>
            }
        </ul>
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/Status/Index.cshtml
@model StatusViewModel
@{
    ViewBag.Title = UIStrings.TVServerStatus;
    Html.jQuery().Enable();
}

@if (Model.HasTAS)
{
    <h2>@UIStrings.Cards</h2>
    <table class="webmp">
        <tr>
            <th>@UIStrings.Card</th>
            <th>@UIStrings.CardName</th>
            <th>@UIStrings.CardState</th>
            <th>@UIStrings.CardGrabbingEPG</th>
            <th>@UIStrings.Channel</th>
            <th>@UIStrings.CardScrambled</th>
            <th>@UIStrings.Username</th>
            <th colspan="2">&nbsp;</th>
        </tr>

        @foreach (var card in Model.Cards)
        {
            <tr>
                <td>@card.CardId</td>
                <td>@card.Name</td>
                <td>@card.State</td>
                <td>@(card.GrabbingEPG ? UIStrings.Yes : UIStrings.No)</td>
                <td>@card.ChannelName</td>
                @if (card.IsActive)
                {
                    <td>@(card.Scrambled ? UIStrings.Yes : UIStrings.No)</td>
                    <td>@card.Username</td>
                    <td>@Html.ActionLink(UIStrings.Stop, "Stop", new { user = card.Username })</td>
                    <td>@Html.ActionLink(UIStrings.Details, "Details", new { user = card.Username })</td>
                }
                else
                {
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </table>
    <br />
}
    
<h2>@UIStrings.DiskInformation</h2>
<table class="webmp">
    <tr>
        <th>@UIStrings.DiskInfoDisk</th>
        <th>@UIStrings.DiskInfoUsed</th>
        <th>@UIStrings.DiskInfoSize</th>
        <th>@UIStrings.DiskInfoAvailable</th>
    </tr>

    @foreach (var disk in Model.DiskInformation.OrderBy(x => x.Disk.StartsWith(@"\\")).ThenBy(x => x.Disk))
    {
        <tr>
            <td>@disk.Disk</td>
            <td>@Math.Round(disk.Used, 1) GB</td>
            <td>@Math.Round(disk.Size, 1) GB</td>
            <td>
                @if((disk.Size > 500 && disk.PercentageUsed > 95) || (disk.Size <= 500 && disk.PercentageUsed > 90))
                {
                    <span style="color: Red;">@Math.Round(100 - @disk.PercentageUsed)%</span>
                } else {
                    @Math.Round(100 - @disk.PercentageUsed)<text>%</text>
                }
            </td>
        </tr>
    }
</table>
<br />

@if (Model.HasSystemInformation)
{
    <text>
    <h2>@UIStrings.SystemStatus</h2>
    <ul>
        <li>@UIStrings.CurrentCPUUsage <span id="cpuUsage">@Model.CpuUsage</span>%</li>
        <li>@UIStrings.CurrentMemoryUsage <span id="memoryUsage">@Model.UsedMemoryMegaBytes</span>MB / @Model.TotalMemoryMegaBytes MB</li>
    </ul>

    <script type="text/javascript">
    $(function () {
        var updateCounters = function (url) {
            $.ajax({ // cannot use $.getJSON() here because it doesn't support setting cache to false
                url: '@Url.Action("GetPerformanceCounters", "Status")',
                dataType: "json",
                cache: false,
                success: function (result) {
                    $("#cpuUsage").html(result.CPU);
                    $("#memoryUsage").html(result.Memory);
                }
            });
        };
        setInterval(updateCounters, 5000);
        updateCounters();
    });
    </script>
    </text>
}