Applications/MPExtended.Applications.WebMediaPortal/Controllers/MusicLibraryController.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Services.Common.Interfaces;
using MPExtended.Services.MediaAccessService.Interfaces;
using MPExtended.Services.StreamingService.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    [ServiceAuthorize]
    public class MusicLibraryController : BaseController
    {
        public ActionResult Index()
        {
            var artistList = Connections.Current.MAS.GetMusicArtistsDetailed(Settings.ActiveSettings.MusicProvider);
            if (artistList == null)
                return new HttpNotFoundResult();
            return View(artistList.Where(x => !String.IsNullOrEmpty(x.Title)));
        }

        public ActionResult Albums(string artist)
        {
            var artistObj = Connections.Current.MAS.GetMusicArtistDetailedById(Settings.ActiveSettings.MusicProvider, artist);
            var albumList = Connections.Current.MAS.GetMusicAlbumsBasicForArtist(Settings.ActiveSettings.MusicProvider, artist);
            return View(new ArtistViewModel()
            {
                Artist = artistObj,
                Albums = albumList.Where(x => !String.IsNullOrEmpty(x.Title))
            });
        }

        public ActionResult Album(string album)
        {
            var albumObj = Connections.Current.MAS.GetMusicAlbumBasicById(Settings.ActiveSettings.MusicProvider, album);
            if (albumObj == null)
                return new HttpNotFoundResult();
            var trackList = Connections.Current.MAS.GetMusicTracksDetailedForAlbum(Settings.ActiveSettings.MusicProvider, album, null, WebSortField.Title, WebSortOrder.Asc);
            var model = new AlbumViewModel()
            {
                Album = albumObj,
                Tracks = trackList.Where(x => !String.IsNullOrEmpty(x.Title))
            };

            return View(AlbumPlayerViewModel.EnableAlbumPlayerForUserAgent(Request.UserAgent) ? "AlbumPlayer" : "Album", model);
        }

        public ActionResult AlbumImage(string album, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.MusicAlbum, album, WebFileType.Cover, width, height, "Images/default/album.png");
        }

        public ActionResult ArtistImage(string artist, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.MusicArtist, artist, WebFileType.Cover, width, height, "Images/default/artist.png");
        }

        public ActionResult TrackImage(string track, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.MusicTrack, track, WebFileType.Cover, width, height, "Images/default/track.png");
        }

        public ActionResult Track(string track)
        {
            var trackObj = Connections.Current.MAS.GetMusicTrackDetailedById(Settings.ActiveSettings.MusicProvider, track);
            if (trackObj == null)
                return new HttpNotFoundResult();
            return View(trackObj);
        }
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Controllers/StreamController.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Applications.WebMediaPortal.Mvc;
using MPExtended.Libraries.Client;
using MPExtended.Libraries.Service;
using MPExtended.Libraries.Service.Config;
using MPExtended.Libraries.Service.Extensions;
using MPExtended.Libraries.Service.Network;
using MPExtended.Libraries.Service.Util;
using MPExtended.Services.MediaAccessService.Interfaces.Music;
using MPExtended.Services.StreamingService.Interfaces;
using MPExtended.Services.Common.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    public class StreamController : BaseController
    {
        // This is the timeout after which streams are automatically killed (in seconds)
        private const int STREAM_TIMEOUT_DIRECT = 10;
        private const int STREAM_TIMEOUT_PROXY = 300;
        private const int STREAM_TIMEOUT_HTTPLIVE = 60;

        // This is the read timeout from the proxy input stream
        private const int STREAM_PROXY_READ_TIMEOUT = 10;

        private static List<string> PlayerOpenedBy = new List<string>();
        private static Dictionary<string, string> RunningStreams = new Dictionary<string, string>();
        private static Dictionary<string, string> HttpLiveUrls = new Dictionary<string, string>();

        // Make this a static property to avoid seeding it with the same time for CreatePlayer() and GenerateStream()
        private static Random randomGenerator = new Random();

        //
        // Util
        protected int? GetProvider(WebMediaType type)
        {
            switch (type)
            {
                case WebMediaType.File:
                    return Settings.ActiveSettings.FileSystemProvider;
                case WebMediaType.Movie:
                    return Settings.ActiveSettings.MovieProvider;
                case WebMediaType.MusicAlbum:
                case WebMediaType.MusicTrack:
                    return Settings.ActiveSettings.MusicProvider;
                case WebMediaType.Picture:
                    return Settings.ActiveSettings.PicturesProvider;
                case WebMediaType.Recording:
                case WebMediaType.TV:
                    return 0;
                case WebMediaType.TVEpisode:
                case WebMediaType.TVSeason:
                case WebMediaType.TVShow:
                    return Settings.ActiveSettings.TVShowProvider;
                default:
                    // this cannot happen
                    return 0;
            }
        }

        protected bool IsUserAuthenticated()
        {
            if (!Configuration.Authentication.Enabled || Configuration.Authentication.UnauthorizedStreams ||
				PlayerOpenedBy.Contains(Request.UserHostAddress) || User.Identity.IsAuthenticated)
                return true;

            // Also allow the user to authenticate through HTTP headers. This is a bit of an ugly hack, but it's a nice way
            // for people to authenticate from scripts etc. 
            if (Request.Headers["Authorization"] != null && Request.Headers["Authorization"].StartsWith("Basic "))
            {
                var content = Request.Headers["Authorization"].Substring(6);
                var details = Encoding.ASCII.GetString(Convert.FromBase64String(content)).Split(':');
                return Configuration.Authentication.Users.Any(x => x.Username == details[0] && x.ValidatePassword(details[1]));
            }

            return false;
        }

        protected WebTranscoderProfile GetProfile(IWebStreamingService streamControl, string defaultProfile)
        {
            string profileName = Request.QueryString["transcoder"] ?? Request.Form["transcoder"] ?? defaultProfile;
            var profile = streamControl.GetTranscoderProfileByName(profileName);
            if (profile != null)
                return profile;

            Log.Error("Warning: Requested non-existing profile {0}; using default {1}", profileName, defaultProfile);
            return streamControl.GetTranscoderProfileByName(defaultProfile);
        }

        protected IWebStreamingService GetStreamControl(WebMediaType type)
        {
            return type == WebMediaType.TV || type == WebMediaType.Recording ? Connections.Current.TASStreamControl : Connections.Current.MASStreamControl;
        }


        protected StreamType GetStreamMode()
        {
            return Settings.ActiveSettings.StreamType != StreamType.DirectWhenPossible ?
                Settings.ActiveSettings.StreamType :
                (NetworkInformation.IsOnLAN(HttpContext.Request.UserHostAddress, false) ? StreamType.Direct : StreamType.Proxied);
        }

        private string GetDefaultProfile(WebMediaType type)
        {
            StreamingProfileType profileType;
            switch (type)
            {
                case WebMediaType.TV:
                case WebMediaType.Recording:
                    profileType = StreamingProfileType.Tv;
                    break;
                case WebMediaType.MusicTrack:
                    profileType = StreamingProfileType.Audio;
                    break;
                default:
                    profileType = StreamingProfileType.Video;
                    break;
            }
            return Configuration.StreamingPlatforms.GetDefaultProfileForUserAgent(profileType, Request.UserAgent);
        }

        //
        // Streaming
        [ServiceAuthorize]
        public ActionResult Download(WebMediaType type, string item)
        {
            // Create URL to GetMediaItem
            Log.Debug("User wants to download type={0}; item={1}", type, item);
            var queryString = HttpUtility.ParseQueryString(String.Empty); // you can't instantiate that class manually for some reason
            queryString["clientDescription"] = String.Format("WebMediaPortal download (user {0})", HttpContext.User.Identity.Name);
            queryString["type"] = ((int)type).ToString();
            queryString["itemId"] = item;
            string address = type == WebMediaType.TV || type == WebMediaType.Recording ? Connections.Current.Addresses.TAS : Connections.Current.Addresses.MAS;
            string fullUrl = String.Format("http://{0}/MPExtended/StreamingService/stream/GetMediaItem?{1}", address, queryString.ToString());
            UriBuilder fullUri = new UriBuilder(fullUrl);

            // If we can access the file without any problems, let IIS stream it; that is a lot faster
            if (NetworkInformation.IsLocalAddress(fullUri.Host, false) && type != WebMediaType.TV)
            {
                var path = type == WebMediaType.Recording ?
                    Connections.Current.TAS.GetRecordingFileInfo(Int32.Parse(item)).Path :
                    Connections.Current.MAS.GetMediaItem(GetProvider(type), type, item).Path[0];
                if (System.IO.File.Exists(path))
                    return File(path, MIME.GetFromFilename(path, "application/octet-stream"), Path.GetFileName(path));
            }

            // If we connect to the services at localhost, actually give the extern IP address to users
            if (NetworkInformation.IsLocalAddress(fullUri.Host, false))
                fullUri.Host = NetworkInformation.GetIPAddress(false);

            // Do the actual streaming
            if (GetStreamMode() == StreamType.Proxied)
            {
                Log.Debug("Proxying download at {0}", fullUri.ToString());
                GetStreamControl(type).AuthorizeStreaming();
                ProxyStream(fullUri.ToString());
            }
            else if (GetStreamMode() == StreamType.Direct)
            {
                Log.Debug("Redirecting user to download at {0}", fullUri.ToString());
                GetStreamControl(type).AuthorizeRemoteHostForStreaming(HttpContext.Request.UserHostAddress);
                return Redirect(fullUri.ToString());
            }
            return new EmptyResult();
        }

        private ActionResult GenerateStream(WebMediaType type, string itemId, int fileindex, string transcoder, int starttime, string continuationId)
        {
            // Check if there is actually a player requested for this stream
            if (!IsUserAuthenticated())
            {
                Log.Warn("User {0} (host {1}) requested a stream but isn't authenticated - denying access to stream", HttpContext.User.Identity.Name, Request.UserHostAddress);
                return new HttpUnauthorizedResult();
            }

            // Delegate to HLS streaming if needed
            WebTranscoderProfile profile = GetStreamControl(type).GetTranscoderProfileByName(transcoder);
            if (profile.HasVideoStream && StreamTarget.GetVideoTargets().First(x => profile.Targets.Contains(x.Name)).Player == VideoPlayer.HLS)
                return GenerateHttpLiveStream(type, itemId, fileindex, profile, starttime, continuationId);

            // Generate random identifier, and continuationId if needed

Applications/MPExtended.Applications.WebMediaPortal/Views/MusicLibrary/Album.cshtml
@model AlbumViewModel
@{
    ViewBag.Title = String.Format(UIStrings.AlbumBy, Model.Album.Title, Model.Album.AlbumArtist);
}

<h2>@String.Format(UIStrings.AlbumBy, Model.Album.Title, Model.Album.AlbumArtist)</h2>

<div>
@foreach (var track in Model.Tracks.OrderBy(x => x.TrackNumber))
{
    <div style="padding: 10px 10px 20px 10px; float:  left; height:  200px;">
        <div>
            <a href="@Url.Action("Track", new { track = track.Id })">
                <img class="img" width="150" src="@Url.Action("TrackImage", "MusicLibrary", new { track = track.Id, width = 150 })" alt="No image" />
            </a>
        </div>
        <div style="padding-top: 5px; overflow: hidden; width:  150px; text-align: center;">@Html.ActionLink(track.Title, "Track", new { track = track.Id })</div>
    </div>
}
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/MusicLibrary/AlbumPlayer.cshtml
@model AlbumViewModel
@{
    ViewBag.Title = String.Format(UIStrings.AlbumBy, Model.Album.Title, Model.Album.AlbumArtist);
}

<h2>@String.Format(UIStrings.AlbumBy, Model.Album.Title, Model.Album.AlbumArtist)</h2>

@{Html.RenderAction("MusicPlayer", "Stream", new { albumId = @Model.Album.Id }); }

Applications/MPExtended.Applications.WebMediaPortal/Views/MusicLibrary/Albums.cshtml
@model ArtistViewModel
@{
	ViewBag.Title = Model.Artist.Title;
}
@Html.Assets().AddViewStylesheet("MusicLibrary/Albums.css")

<h3>@String.Format(UIStrings.AlbumsFromArtist, Model.Artist.Title)</h3>

@foreach (var album in Model.Albums)
{
    <div style="padding: 10px 10px 20px 10px; float: left; height: 200px;">
        <div>
            <a href="@Url.Action("Album", new { album = album.Id })">
                <img height="150" width="150" src="@Url.Action("AlbumImage", "MusicLibrary", new { album = album.Id, width = 150 })" />
            </a>
        </div>
        <div style="padding-top: 5px; overflow: hidden; width:  150px; text-align: center;">
            @Html.ActionLink(album.Title, "Album", new { album = album.Id })
        </div>
    </div>
}

Applications/MPExtended.Applications.WebMediaPortal/Views/MusicLibrary/Index.cshtml
@model IEnumerable<MPExtended.Services.MediaAccessService.Interfaces.Music.WebMusicArtistDetailed>
@{
	ViewBag.Title = UIStrings.Music;
}

<h2>@UIStrings.YourArtists</h2>

<div>
    @foreach (var artist in Model)
    {
        <div id="MusicBox" style="padding: 10px 10px 20px 10px; float: left; height: 200px;">
            <div>
                <a href="@Url.Action("Albums", new { artist = artist.Id })">
                    <img class="img" width="150" src="@Url.Action("ArtistImage", "MusicLibrary", new { artist = artist.Id, width = 150 })" alt="No image" /> 
                </a>
            </div>
            <div id="musicText" style="padding-top: 5px; overflow: hidden; width: 150px; text-align: center;">
                @Html.ActionLink(artist.Title, "Albums", new { artist = artist.Id })
            </div>
        </div>
    }
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/MusicLibrary/Track.cshtml
@model MPExtended.Services.MediaAccessService.Interfaces.Music.WebMusicTrackDetailed
@{
    ViewBag.Title = String.Format(UIStrings.ListeningTrack, Model.Title);
}

<h2>@UIStrings.Play</h2>
@Html.Raw(String.Format(UIStrings.YouAreListening, Model.Title, Model.Artist.First()))
<br /><br />

@{
    Html.RenderAction("Player", "Stream", new
    {
        type = MPExtended.Services.Common.Interfaces.WebMediaType.MusicTrack,
        itemId = Model.Id
    });
}