Applications/MPExtended.Applications.WebMediaPortal/Controllers/StreamController.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Applications.WebMediaPortal.Mvc;
using MPExtended.Libraries.Client;
using MPExtended.Libraries.Service;
using MPExtended.Libraries.Service.Config;
using MPExtended.Libraries.Service.Extensions;
using MPExtended.Libraries.Service.Network;
using MPExtended.Libraries.Service.Util;
using MPExtended.Services.MediaAccessService.Interfaces.Music;
using MPExtended.Services.StreamingService.Interfaces;
using MPExtended.Services.Common.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    public class StreamController : BaseController
    {
        // This is the timeout after which streams are automatically killed (in seconds)
        private const int STREAM_TIMEOUT_DIRECT = 10;
        private const int STREAM_TIMEOUT_PROXY = 300;
        private const int STREAM_TIMEOUT_HTTPLIVE = 60;

        // This is the read timeout from the proxy input stream
        private const int STREAM_PROXY_READ_TIMEOUT = 10;

        private static List<string> PlayerOpenedBy = new List<string>();
        private static Dictionary<string, string> RunningStreams = new Dictionary<string, string>();
        private static Dictionary<string, string> HttpLiveUrls = new Dictionary<string, string>();

        // Make this a static property to avoid seeding it with the same time for CreatePlayer() and GenerateStream()
        private static Random randomGenerator = new Random();

        //
        // Util
        protected int? GetProvider(WebMediaType type)
        {
            switch (type)
            {
                case WebMediaType.File:
                    return Settings.ActiveSettings.FileSystemProvider;
                case WebMediaType.Movie:
                    return Settings.ActiveSettings.MovieProvider;
                case WebMediaType.MusicAlbum:
                case WebMediaType.MusicTrack:
                    return Settings.ActiveSettings.MusicProvider;
                case WebMediaType.Picture:
                    return Settings.ActiveSettings.PicturesProvider;
                case WebMediaType.Recording:
                case WebMediaType.TV:
                    return 0;
                case WebMediaType.TVEpisode:
                case WebMediaType.TVSeason:
                case WebMediaType.TVShow:
                    return Settings.ActiveSettings.TVShowProvider;
                default:
                    // this cannot happen
                    return 0;
            }
        }

        protected bool IsUserAuthenticated()
        {
            if (!Configuration.Authentication.Enabled || Configuration.Authentication.UnauthorizedStreams ||
				PlayerOpenedBy.Contains(Request.UserHostAddress) || User.Identity.IsAuthenticated)
                return true;

            // Also allow the user to authenticate through HTTP headers. This is a bit of an ugly hack, but it's a nice way
            // for people to authenticate from scripts etc. 
            if (Request.Headers["Authorization"] != null && Request.Headers["Authorization"].StartsWith("Basic "))
            {
                var content = Request.Headers["Authorization"].Substring(6);
                var details = Encoding.ASCII.GetString(Convert.FromBase64String(content)).Split(':');
                return Configuration.Authentication.Users.Any(x => x.Username == details[0] && x.ValidatePassword(details[1]));
            }

            return false;
        }

        protected WebTranscoderProfile GetProfile(IWebStreamingService streamControl, string defaultProfile)
        {
            string profileName = Request.QueryString["transcoder"] ?? Request.Form["transcoder"] ?? defaultProfile;
            var profile = streamControl.GetTranscoderProfileByName(profileName);
            if (profile != null)
                return profile;

            Log.Error("Warning: Requested non-existing profile {0}; using default {1}", profileName, defaultProfile);
            return streamControl.GetTranscoderProfileByName(defaultProfile);
        }

        protected IWebStreamingService GetStreamControl(WebMediaType type)
        {
            return type == WebMediaType.TV || type == WebMediaType.Recording ? Connections.Current.TASStreamControl : Connections.Current.MASStreamControl;
        }


        protected StreamType GetStreamMode()
        {
            return Settings.ActiveSettings.StreamType != StreamType.DirectWhenPossible ?
                Settings.ActiveSettings.StreamType :
                (NetworkInformation.IsOnLAN(HttpContext.Request.UserHostAddress, false) ? StreamType.Direct : StreamType.Proxied);
        }

        private string GetDefaultProfile(WebMediaType type)
        {
            StreamingProfileType profileType;
            switch (type)
            {
                case WebMediaType.TV:
                case WebMediaType.Recording:
                    profileType = StreamingProfileType.Tv;
                    break;
                case WebMediaType.MusicTrack:
                    profileType = StreamingProfileType.Audio;
                    break;
                default:
                    profileType = StreamingProfileType.Video;
                    break;
            }
            return Configuration.StreamingPlatforms.GetDefaultProfileForUserAgent(profileType, Request.UserAgent);
        }

        //
        // Streaming
        [ServiceAuthorize]
        public ActionResult Download(WebMediaType type, string item)
        {
            // Create URL to GetMediaItem
            Log.Debug("User wants to download type={0}; item={1}", type, item);
            var queryString = HttpUtility.ParseQueryString(String.Empty); // you can't instantiate that class manually for some reason
            queryString["clientDescription"] = String.Format("WebMediaPortal download (user {0})", HttpContext.User.Identity.Name);
            queryString["type"] = ((int)type).ToString();
            queryString["itemId"] = item;
            string address = type == WebMediaType.TV || type == WebMediaType.Recording ? Connections.Current.Addresses.TAS : Connections.Current.Addresses.MAS;
            string fullUrl = String.Format("http://{0}/MPExtended/StreamingService/stream/GetMediaItem?{1}", address, queryString.ToString());
            UriBuilder fullUri = new UriBuilder(fullUrl);

            // If we can access the file without any problems, let IIS stream it; that is a lot faster
            if (NetworkInformation.IsLocalAddress(fullUri.Host, false) && type != WebMediaType.TV)
            {
                var path = type == WebMediaType.Recording ?
                    Connections.Current.TAS.GetRecordingFileInfo(Int32.Parse(item)).Path :
                    Connections.Current.MAS.GetMediaItem(GetProvider(type), type, item).Path[0];
                if (System.IO.File.Exists(path))
                    return File(path, MIME.GetFromFilename(path, "application/octet-stream"), Path.GetFileName(path));
            }

            // If we connect to the services at localhost, actually give the extern IP address to users
            if (NetworkInformation.IsLocalAddress(fullUri.Host, false))
                fullUri.Host = NetworkInformation.GetIPAddress(false);

            // Do the actual streaming
            if (GetStreamMode() == StreamType.Proxied)
            {
                Log.Debug("Proxying download at {0}", fullUri.ToString());
                GetStreamControl(type).AuthorizeStreaming();
                ProxyStream(fullUri.ToString());
            }
            else if (GetStreamMode() == StreamType.Direct)
            {
                Log.Debug("Redirecting user to download at {0}", fullUri.ToString());
                GetStreamControl(type).AuthorizeRemoteHostForStreaming(HttpContext.Request.UserHostAddress);
                return Redirect(fullUri.ToString());
            }
            return new EmptyResult();
        }

        private ActionResult GenerateStream(WebMediaType type, string itemId, int fileindex, string transcoder, int starttime, string continuationId)
        {
            // Check if there is actually a player requested for this stream
            if (!IsUserAuthenticated())
            {
                Log.Warn("User {0} (host {1}) requested a stream but isn't authenticated - denying access to stream", HttpContext.User.Identity.Name, Request.UserHostAddress);
                return new HttpUnauthorizedResult();
            }

            // Delegate to HLS streaming if needed
            WebTranscoderProfile profile = GetStreamControl(type).GetTranscoderProfileByName(transcoder);
            if (profile.HasVideoStream && StreamTarget.GetVideoTargets().First(x => profile.Targets.Contains(x.Name)).Player == VideoPlayer.HLS)
                return GenerateHttpLiveStream(type, itemId, fileindex, profile, starttime, continuationId);

            // Generate random identifier, and continuationId if needed

Applications/MPExtended.Applications.WebMediaPortal/Controllers/TVShowsLibraryController.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Services.Common.Interfaces;
using MPExtended.Services.MediaAccessService.Interfaces;
using MPExtended.Services.MediaAccessService.Interfaces.TVShow;
using MPExtended.Services.StreamingService.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    [ServiceAuthorize]
    public class TVShowsLibraryController : BaseController
    {
        // Series
        public ActionResult Index(string filter = null)
        {
            var shows = Connections.Current.MAS.GetTVShowsDetailed(Settings.ActiveSettings.TVShowProvider, filter, WebSortField.Title, WebSortOrder.Asc)
                .Where(x => !String.IsNullOrEmpty(x.Title));
            return View(shows);
        }

        public ActionResult ShowInfo(string show)
        {
            var model = new TVShowViewModel(show);
            if (model.Show == null)
                return HttpNotFound();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SeriesFanart(string show, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Backdrop, width, height, "Images/default/tvshow-fanart.png");
        }

        public ActionResult SeriesPoster(string show, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Poster, width, height, "Images/default/tvshow-poster.png");
        }

        public ActionResult SeriesBanner(string show, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Banner, width, height, "Images/default/tvshow-banner.png");
        }

        // Seasons
        public ActionResult Seasons(string show)
        {
            var model = new TVShowViewModel(show);
            if (model.Show == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult SeasonInfo(string season)
        {
            var model = new TVSeasonViewModel(season);
            if (model.Season == null)
                return HttpNotFound();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SeasonImage(string season, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.TVSeason, season, WebFileType.Banner, width, height, "Images/default/tvseason-banner.png");
        }

        // Episodes
        public ActionResult Episodes(string season)
        {
            var model = new TVSeasonViewModel(season);
            if (model.Season == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult Details(string episode)
        {
            var model = new TVEpisodeViewModel(episode);
            if (model.Episode == null)
                return HttpNotFound();

            ViewBag.ShowPlay = model.Episode.Path.Count > 0;
            return View(model);
        }

        public ActionResult EpisodeInfo(string episode)
        {
            var model = new TVEpisodeViewModel(episode);
            if (model.Episode == null)
                return HttpNotFound();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Play(string episode)
        {
            var model = new TVEpisodeViewModel(episode);
            if (model.Episode == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult EpisodeImage(string episode, int width = 0, int height = 0)
        {
            return Images.ReturnFromService(WebMediaType.TVEpisode, episode, WebFileType.Banner, width, height, "Images/default/tvepisode-banner.png");
        }
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Details.cshtml
@model TVEpisodeViewModel
@{
    ViewBag.Title = @Model.Episode.Title;
}

<h2>@Model.Episode.Title</h2>

<div class="imageColumn">
    <img src="@Url.Action("EpisodeImage", new { episode = @Model.Episode.Id, width = 300 })" width="300" alt="No image" />
</div>
<div class="dataColumn">
    <ul>
        <li>@UIStrings.WrittenBy
            <ul>
                @foreach (string writer in Model.Episode.Writers)
                {
                    <li>@writer</li>
                }
            </ul>
        </li>

        <li>@UIStrings.GuestStarring
            <ul>
                @foreach (string guestStar in Model.Episode.GuestStars)
                {
                    <li>@guestStar</li>
                }
            </ul>        
        </li>

        <li>@String.Format(UIStrings.Aired, Model.Episode.FirstAired.ToShortDateString())</li>

        @if(ViewBag.ShowPlay) {
            <li>@Model.FullQuality</li>
            <li>@Html.ActionLink(UIStrings.Download, "Download", "Stream", new { item = Model.Episode.Id, type = Model.Episode.Type }, new { })</li>
            <li>@Html.ActionLink(UIStrings.Play, "Play", new { episode = Model.Episode.Id })</li>
        }
    </ul>
</div>

<div class="textColumn">
    @Model.Episode.Summary
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Episodes.cshtml
@model TVSeasonViewModel
@{
    var header = Model.Season.SeasonNumber == 0 ? 
        String.Format("{0} {1}", Model.Show.Title, UIStrings.Specials) : 
        String.Format(UIStrings.ShowSeason, Model.Show.Title, Model.Season.SeasonNumber);
    ViewBag.Title = header;    
}

<h2>@header</h2>

<div class="imageColumn">
    <img src="@Url.Action("SeasonImage", new { season = @Model.Season.Id, width = 500 })" width="500" alt="No image" />
</div>

<div class="listColumn">
    <ul>
        @foreach (var episode in Model.Episodes)
        {
            <li>@Html.ActionLink(String.Format(UIStrings.EpisodeDisplay, episode.EpisodeNumber, episode.Title), "Details", new { episode = episode.Id })</li>   
        }
    </ul>
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Index.cshtml
@model IEnumerable<MPExtended.Services.MediaAccessService.Interfaces.TVShow.WebTVShowDetailed>
@{
	ViewBag.Title = UIStrings.TVShows;
}

<h2>@UIStrings.YourTVShows</h2>

<div>
    @foreach (var show in Model)
    {
        <div style="float: left;">
            <div style="padding: 0px 5px 0px 5px;">
                <a href="@Url.Action("Seasons", "TVShowsLibrary", new { show = show.Id })">
                    <img width="300" src="@Url.Action("SeriesBanner", new { show = @show.Id, width = 300 })" alt="No image" />
                </a>
            </div>
            <div style="text-align: center; padding-bottom: 20px;">@Html.ActionLink(show.Title, "Seasons", new { show = show.Id })</div>       
        </div>
    }
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Play.cshtml
@model TVEpisodeViewModel
@{
    ViewBag.Title = String.Format(UIStrings.WatchingEpisode, Model.Episode.Title, Model.Show.Title);
}

<h2>@UIStrings.Play</h2>
@Html.Raw(String.Format(UIStrings.YouAreWatchingEpisode, Model.Show.Title, Model.Season.SeasonNumber, Model.Episode.EpisodeNumber, Model.Episode.Title))
<br /><br />

@{Html.RenderAction("Player", "Stream", new
  {
      type = MPExtended.Services.Common.Interfaces.WebMediaType.TVEpisode,
      itemId = @Model.Episode.Id
  });
}

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Seasons.cshtml
@model TVShowViewModel
@{
    ViewBag.Title = Model.Show.Title;
}

<h2>@Model.Show.Title</h2>

<div class="imageColumn extended">
    <img src="@Url.Action("SeriesPoster", new { show = Model.Show.Id, width = 500 })" width="500" alt="No image" />
</div>

<div>
    @foreach (var season in Model.Seasons)
    {
        <div class="seasonWrap" style="float: left; padding: 10px;">
            <a href="@Url.Action("Episodes", new { season = season.Id })">
                <img class="seasonPoster" src="@Url.Action("SeasonImage", new { season = season.Id, width = 100 })" width="100" alt="No image" />
            </a>
            <a style="text-align: center;" href="@Url.Action("Episodes", new { season = season.Id })">
                <div class="seasonTitle">@String.Format(season.SeasonNumber == 0 ? UIStrings.Specials : UIStrings.Season, season.SeasonNumber)<br />@season.Year</div>
            </a>
        </div>
    }
</div>