Applications/MPExtended.Applications.WebMediaPortal/Models/ScheduleViewModels.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Mvc;
using MPExtended.Services.TVAccessService.Interfaces;
using MPExtended.Applications.WebMediaPortal.Strings;
using MPExtended.Services.Common.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Models
{
    public class ScheduleViewModel
    {
        public static Dictionary<WebScheduleType, string> ScheduleTypeNames = new Dictionary<WebScheduleType, string>()
            {
                { WebScheduleType.Once, FormStrings.ScheduleTypeOnce },
                { WebScheduleType.Daily, FormStrings.ScheduleTypeDaily },
                { WebScheduleType.Weekly, FormStrings.ScheduleTypeWeekly },
                { WebScheduleType.EveryTimeOnThisChannel, FormStrings.ScheduleTypeEveryTimeOnThisChannel },
                { WebScheduleType.EveryTimeOnEveryChannel, FormStrings.ScheduleTypeEveryTimeOnEveryChannel },
                { WebScheduleType.Weekends, FormStrings.ScheduleTypeWeekends },
                { WebScheduleType.WorkingDays, FormStrings.ScheduleTypeWorkingDays },
                { WebScheduleType.WeeklyEveryTimeOnThisChannel, FormStrings.ScheduleTypeWeeklyOnThisChannel }
            };

        public int ProgramId { get; set; }
        public int Id { get; set; }

        [StringLength(255)]
        [LocalizedDisplayName(typeof(FormStrings), "ScheduleTitle")]
        [Required(ErrorMessageResourceType = typeof(FormStrings), ErrorMessageResourceName = "FieldRequired")]
        public string Title { get; set; }

        [LocalizedDisplayName(typeof(FormStrings), "ScheduleStartTime")]
        [Required(ErrorMessageResourceType = typeof(FormStrings), ErrorMessageResourceName = "FieldRequired")]
        public DateTime? StartTime { get; set; }

        [LocalizedDisplayName(typeof(FormStrings), "ScheduleEndTime")]
        [Required(ErrorMessageResourceType = typeof(FormStrings), ErrorMessageResourceName = "FieldRequired")]
        public DateTime? EndTime { get; set; }
   
        [LocalizedDisplayName(typeof(FormStrings), "ScheduleType")]
        [ListChoice("ScheduleTypeList", AllowNull = false, ErrorMessageResourceType = typeof(FormStrings), ErrorMessageResourceName = "ScheduleSelectValidType")]
        public WebScheduleType ScheduleType { get; set; }

        [LocalizedDisplayName(typeof(FormStrings), "ScheduleChannel")]
        [ListChoice("ChannelList", AllowNull = false, ErrorMessageResourceType = typeof(FormStrings), ErrorMessageResourceName = "ScheduleSelectValidChannel")]
        public int Channel { get; set; }

        public string ChannelName { get; private set; }
        public string StartTimeFormatted { get; private set; }
        public string EndTimeFormatted { get; private set; }

        public IEnumerable<SelectListItem> ChannelList
        {
            get
            {
                return Connections.Current.TAS.GetChannelsDetailed(sort: WebSortField.Title)
                        .Where(x => x.VisibleInGuide)
                        .Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.Title });
            }
        }

        public string ScheduleTypeName
        {
            get
            {
                return ScheduleTypeNames[ScheduleType];
            }
        }

        public IEnumerable<SelectListItem> ScheduleTypeList
        {
            get
            {
                return ScheduleTypeNames.Select(x => new SelectListItem() { Value = x.Key.ToString(), Text = x.Value });
            }
        }

        public bool IsFromProgram
        {
            get
            {
                return ProgramId != 0;
            }
        }

        public ScheduleViewModel()
        {
            StartTime = null;
            EndTime = null;
        }

        private ScheduleViewModel(DateTime startTime, DateTime endTime, string title, int channelId)
        {
            StartTime = startTime;
            EndTime = endTime;
            Title = title;
            Channel = channelId;
        }

        public ScheduleViewModel(WebProgramDetailed program)
            : this (program.StartTime, program.EndTime, program.Title, program.ChannelId)
        {
            ProgramId = program.Id;

            ChannelName = Connections.Current.TAS.GetChannelDetailedById(program.ChannelId).Title;
        }

        public ScheduleViewModel(WebScheduleBasic schedule)
            : this (schedule.StartTime, schedule.EndTime, schedule.Title, schedule.ChannelId)
        {
            Id = schedule.Id;
            ScheduleType = schedule.ScheduleType;

            switch (ScheduleType)
            {
                case WebScheduleType.Daily:
                case WebScheduleType.EveryTimeOnThisChannel:
                case WebScheduleType.Once:
                case WebScheduleType.Weekends:
                case WebScheduleType.Weekly:
                case WebScheduleType.WeeklyEveryTimeOnThisChannel:
                case WebScheduleType.WorkingDays:
                    ChannelName = Connections.Current.TAS.GetChannelDetailedById(schedule.ChannelId).Title;
                    break;
                case WebScheduleType.EveryTimeOnEveryChannel:
                    ChannelName = "";
                    break;
            }

            switch (ScheduleType)
            {
                case WebScheduleType.Daily:
                case WebScheduleType.Weekends:
                case WebScheduleType.WorkingDays:
                    StartTimeFormatted = StartTime.Value.ToString("t");
                    EndTimeFormatted = EndTime.Value.ToString("t");
                    break;
                case WebScheduleType.Weekly:
                    StartTimeFormatted = StartTime.Value.ToString("dddd") + " " + StartTime.Value.ToString("t");
                    EndTimeFormatted = EndTime.Value.ToString("dddd") + " " + EndTime.Value.ToString("t");
                    break;
                case WebScheduleType.Once:
                default:
                    StartTimeFormatted = StartTime.Value.ToString("g");
                    EndTimeFormatted = EndTime.Value.ToString("g");
                    break;
                case WebScheduleType.WeeklyEveryTimeOnThisChannel:
                    StartTimeFormatted = StartTime.Value.ToString("dddd");
                    break;
                case WebScheduleType.EveryTimeOnEveryChannel:
                case WebScheduleType.EveryTimeOnThisChannel:
                    // they don't have a time associated with them
                    break;
            }
        }
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Controllers/ScheduleController.cs
#region Copyright (C) 2011-2013 MPExtended
// Copyright (C) 2011-2013 MPExtended Developers, http://www.mpextended.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Services.TVAccessService.Interfaces;
using MPExtended.Services.Common.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    [ServiceAuthorize]
    public class ScheduleController : BaseController
    {
        //
        // GET: /Schedule/
        public ActionResult Index()
        {
            var list = Connections.Current.TAS.GetSchedules(null, WebSortField.Title, WebSortOrder.Asc).Select(x => new ScheduleViewModel(x));
            return View(list);
        }

        public ActionResult DeleteSchedule(int programId)
        {
            var program = Connections.Current.TAS.GetProgramDetailedById(programId);
            int id = Connections.Current.TAS.GetSchedules().Where(p => p.ChannelId == program.ChannelId && p.StartTime == program.StartTime && p.EndTime == program.EndTime).First().Id;
            Connections.Current.TAS.DeleteSchedule(id);
            return RedirectToAction("ProgramDetails", "Television", new { programId = programId });
        }

        public ActionResult DeleteScheduleById(int id)
        {
            Connections.Current.TAS.DeleteSchedule(id);
            return RedirectToAction("Index");
        }

        public ActionResult AddSchedule(int? programId = null)
        {
            if (programId != null && programId != 0)
            {
                var program = Connections.Current.TAS.GetProgramDetailedById(programId.Value);
                if (program == null)
                {
                    return HttpNotFound();
                }
                return View("AddScheduleByProgram", new ScheduleViewModel(program));
            }
            else
            {
                return View("AddScheduleForm", new ScheduleViewModel());
            }
        }

        public ActionResult EditSchedule(int id)
        {
            var schedule = Connections.Current.TAS.GetScheduleById(id);
            return View(new ScheduleViewModel(schedule));
        }

        [HttpPost]
        public ActionResult Save(ScheduleViewModel model)
        {
            // show view again if user failed to fill in correctly
            if (!ModelState.IsValid)
            {
                return AddSchedule(model.ProgramId);
            }

            // delete old schedule if this is an edit
            if (model.Id != 0)
            {
                Connections.Current.TAS.DeleteSchedule(model.Id);
            }

            // add schedule
            Connections.Current.TAS.AddSchedule(model.Channel, model.Title, model.StartTime.Value, model.EndTime.Value, model.ScheduleType);

            // redirect
            if (model.ProgramId != 0)
            {
                return RedirectToAction("ProgramDetails", "Television", new { programId = model.ProgramId });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/Schedule/AddScheduleByProgram.cshtml
@model ScheduleViewModel
@{
    ViewBag.Title = UIStrings.AddSchedule;
}

<h2>@UIStrings.AddSchedule</h2>
@using (Html.BeginForm("Save", "Schedule"))
{
    @Html.HiddenFor(model => model.ProgramId)

    @Html.ValidationSummary(false)
    <br />
    
    <table class="webmp">
        <tr>
            <td>
                @Html.LabelFor(model => model.Title)
            </td>
            <td>
                @Html.DisplayFor(model => model.Title)
                @Html.HiddenFor(model => model.Title)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.Channel)
            </td>
            <td>
                @Html.DisplayFor(model => model.ChannelName)
                @Html.HiddenFor(model => model.Channel)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.StartTime)
            </td>
            <td>
                @Html.DisplayFor(model => model.StartTime)
                @Html.HiddenFor(model => model.StartTime)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.EndTime)
            </td>
            <td>
                @Html.DisplayFor(model => model.EndTime)
                @Html.HiddenFor(model => model.EndTime)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.ScheduleType)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ScheduleType)
                @Html.ValidationMessageFor(model => model.ScheduleType)
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <input type="submit" value="@UIStrings.Create" />
            </td>
        </tr>
    </table>
}

Applications/MPExtended.Applications.WebMediaPortal/Views/Schedule/AddScheduleForm.cshtml
@model ScheduleViewModel
@{
    ViewBag.Title = UIStrings.AddSchedule;
}

<h2>@UIStrings.AddSchedule</h2>
@Html.Partial("_Form")

Applications/MPExtended.Applications.WebMediaPortal/Views/Schedule/EditSchedule.cshtml
@model ScheduleViewModel
@{
    ViewBag.Title = UIStrings.EditSchedule;
}

<h2>@UIStrings.EditSchedule</h2>
@Html.Partial("_Form")

Applications/MPExtended.Applications.WebMediaPortal/Views/Schedule/Index.cshtml
@model IEnumerable<ScheduleViewModel>
@{
    ViewBag.Title = UIStrings.Schedules;
}

<h2>@UIStrings.Schedules</h2>

<table class="webmp">
    <tr>
        <th>@UIStrings.Program</th>
        <th>@UIStrings.ScheduleHeaderRepetition</th>
		<th>@UIStrings.Channel</th>
        <th>@UIStrings.ScheduleHeaderStartTime</th>
        <th>@UIStrings.ScheduleHeaderEndTime</th>
        <th colspan="2"></th>
    </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(x => item.Title)</td>
            <td>@item.ScheduleTypeName</td>
            <td>@Html.DisplayFor(x => item.ChannelName)</td>
            <td>@Html.DisplayFor(x => item.StartTimeFormatted)</td>
            <td>@Html.DisplayFor(x => item.EndTimeFormatted)</td>
            <td>
                @Html.ActionLink(UIStrings.Delete, "DeleteScheduleById", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink(UIStrings.Edit, "EditSchedule", new { id = item.Id }) 
            </td>
        </tr>
    }
</table>

<br />
@Html.ActionLink(UIStrings.AddSchedule, "AddSchedule")

Applications/MPExtended.Applications.WebMediaPortal/Views/Schedule/_Form.cshtml
@model ScheduleViewModel
@using (Html.BeginForm("Save", "Schedule"))
{
    @Html.HiddenFor(model => model.Id)
    
    @Html.ValidationSummary(false)
    <br />
    
    <table class="webmp">
        <tr>
            <td>
                @Html.LabelFor(model => model.Title)
            </td>
            <td>
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.Channel)
            </td>
            <td>
                @Html.DropDownListFor(model => model.Channel)
                @Html.ValidationMessageFor(model => model.Channel)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.StartTime)
            </td>
            <td>
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.EndTime)
            </td>
            <td>
                @Html.EditorFor(model => model.EndTime)
                @Html.ValidationMessageFor(model => model.EndTime)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(model => model.ScheduleType)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ScheduleType)
                @Html.ValidationMessageFor(model => model.ScheduleType)
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <input type="submit" value="@UIStrings.Save" />
            </td>
        </tr>
    </table>
}